
    Write-Host "============================================================================================"
    Write-Host "--------------------------------------------------------------------------------------------"
    Write-Host "-------------------------------------Não esqueça de:----------------------------------"
    Write-Host "--------------------------------------------------------------------------------------------"
    Write-Host "1. Colocar apenas os apps necessários na barra de tarefas"
    Write-Host "2. Colocar o Google Chrome como navegador e o Adobe reader como padrão de documentos .PDF"
    Write-Host "============================================================================================"
    Write-Host ""
    Write-Host ""
    Write-Host ""
